CREATE TABLE IF NOT EXISTS `slm_users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `login` TEXT NULL COMMENT '',
  `secret` LONGTEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

